### ISSUE TITLE
db enormous growth

### ISSUE THREAD

**Issue by nikandfor** [syndtr/goleveldb#161] opened 2016-12-15 16:48 UTC
When I do "random" inserts like in this gist db grows enormously and compacts does not help.
https://gist.github.com/nikandfor/320390df76cee1decff8660b04623ce0

**Comment by ThibaultRiviere** [comment] 2016-12-15 19:58
@nikandfor The compaction is to go through an level to an other one in the LSM .
I don't know if it is by default or configurable, but if it is try the snappy algorithm.
It will does some compression, i think this is what you want .

**Comment by nikandfor** [comment] 2016-12-16 01:16
The problem is that some sequence of operations (inside "double" switch case in my gist) growths db x5, x10 and more by disk usage without any data addition. This returned to normal after db reopen.

In my example I've created db with 50M keys with 128 bytes value and 50M keys with nil value.
After that I iterate over first set of keys and copy value to second set. In time of this db grows from 125Mb to 857Mb.
Than I restart the program, db shrinks back to 164Mb, I iterate again and read value of first keys set and compare them with values from second set. In time of this db grows from 164Mb to 1.4Gb.
On third time db growths from 165Mb to 2.2Gb

This is not good.

**Comment by syndtr** [comment] 2016-12-16 02:06
Thanks for raising this to my attention. 

When iterator is created it locks a "version" ("version"  holds the immutable *sstable*), which also locks subsequent "version", when a compaction is committed it will creates a new "version", the problem is the intermediate "versions" won't get released as long as the old "version" still locked. Probably put reference counter on *sstable* files instead of "version" would be better, that way unused  *sstable* files can be removed immediately.

**Comment by nikandfor** [comment] 2016-12-16 05:08
On the third run program does not Put anything to db, but it grows the most of previous runs. That is the most interesting thing

**Closed** 2016-12-27 11:07 UTC
Labels: bug

**Comment by nikandfor** [comment] 2016-12-27 12:49
It's helps. Thank you
