### ISSUE TITLE
Opening a transaction will freeze all other db transactions

### ISSUE THREAD

**Issue by randombenj** [syndtr/goleveldb#431] opened 2023-05-01 15:14 UTC
When opening a transaction, any other `Put` operation will freeze the execution:

To reproduce the issue create a simple go module:

```sh
go mod init leveld-issue
go get github.com/syndtr/goleveldb/leveldb
# add main.go from below
go run main.go
```

```go
package main

import (
	"fmt"

	"github.com/syndtr/goleveldb/leveldb"
)

func main() {
	fmt.Println(" => opening db")
	db, _ := leveldb.OpenFile("db", nil)
	defer db.Close()

	transaction, _ := db.OpenTransaction()
	defer transaction.Discard()

	fmt.Println(" -> [transaction] putting A1")
	transaction.Put([]byte("A1"), []byte("value"), nil)

	// now even if we want to put something into the database
	// it will freeze!
	// if `db.Put(...)` is removed, the program will run fine ...
	fmt.Println(" -> putting A2")
	db.Put([]byte("A2"), []byte("value"), nil) // <-- will freeze here!

	// will never be reached
	fmt.Println(" -> [transaction] commit")
	transaction.Commit()
}

```

**Comment by qianbin** [comment] 2023-05-02 13:35
It's not a bug. As the comment said，`Subsequent call to Write and OpenTransaction will be blocked until in-flight transaction is committed or discarded`. https://github.com/syndtr/goleveldb/blob/126854af5e6d8295ef8e8bee3040dd8380ae72e8/leveldb/db_transaction.go#L284-L288

**Comment by randombenj** [comment] 2023-05-02 14:05
Okay, thanks for clarifying 👍

**Closed as completed** 2023-05-02 14:07 UTC
